name: is_null
description: Using `.isNull` rather than `== null`
version: 1.0.0
repository: https://github.com/ethicnology/dart-is-null

environment:
  sdk: ^3.2.0

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
